Baby, Donny:		donnybaby@ny.cmbchina.com
Barrett, Heather:		heatherbarrett@ny.cmbchina.com
Benavides, Jose:		JoseBenavides@ny.cmbchina.com
Chan, Amy:		amychan@ny.cmbchina.com
Chan, ChakMan:		ChakManChan@ny.cmbchina.com
Chan, Joe:		JoeChan@ny.cmbchina.com
Chan, Lillian:		lillianchan@ny.cmbchina.com
Chen, Alicia:		AliciaChen@ny.cmbchina.com
Chen, Han:		hanchen@ny.cmbchina.com
Chen, Jingwen:		jingwenchen@ny.cmbchina.com
Chen, Liang:		liangchen@ny.cmbchina.com
Chen, Michael:		michaelchen@ny.cmbchina.com
Chen, Yezi:		yezichen@ny.cmbchina.com
Chin, Carmen:		carmenchin@ny.cmbchina.com
Chung, Jasmine:		jasminechung@ny.cmbchina.com
Da, Ling:		lingda@ny.cmbchina.com
Ding, Cecilia:		xiaoxiding@ny.cmbchina.com
Ding, Kevin:		kevinding@ny.cmbchina.com
Ding, Ting:		tingding@ny.cmbchina.com
Dong, Hang:		HangDong@ny.cmbchina.com
Duan, Lian:		lianduan@ny.cmbchina.com
E, Chen:		echen@ny.cmbchina.com
Fan, Wengirl:		wengefan@ny.cmbchina.com
Ferrara, Anthony:		AnthonyFerrara@ny.cmbchina.com
Friedland, Keith:		keithfriedland@ny.cmbchina.com
Fu, James:		jamesfu@ny.cmbchina.com
Gao, Mu:		MuGao@ny.cmbchina.com
Ge, Brenda:		xinge@ny.cmbchina.com
Ge, Travis:		travisge@ny.cmbchina.com
Geramian, Majid:		majidgeramian@ny.cmbchina.com
Giraldo, Jacqueline:		jacquelinegiraldo@ny.cmbchina.com
Gu, Shirley:		shirleygu@ny.cmbchina.com
Guan, Ruiqing:		ruiqingguan@ny.cmbchina.com
Guo, Yaoyao:		YaoyaoGuo@ny.cmbchina.com
Han, Andrea:		andreahan@ny.cmbchina.com
Han, Sarah:		sarahhan@ny.cmbchina.com
Hemmann, J.Mark:		markhemmann@ny.cmbchina.com
Howard Qi:		HowardQi@ny.cmbchina.com
Hu, Axl:		AxlHu@ny.cmbchina.com
Hu, Frank:		jiehu@ny.cmbchina.com
Hu, Harry:		harryhu@ny.cmbchina.com
Huang, Bill:		biaohuang@ny.cmbchina.com
Hur, Leslie:		LeslieHur@ny.cmbchina.com
Ji, Tim:		tongji@ny.cmbchina.com
Jia, Longmei:		LongmeiJia@ny.cmbchina.com
Jiang, Jessica:		wenwenjiang@ny.cmbchina.com
Jiang, Yan:		yanjiang@ny.cmbchina.com
Jiao, Chengyue:		chengyuejiao@ny.cmbchina.com
Jin, Kimberly:		kimberlyjin@ny.cmbchina.com
Jin, Ming:		MingJin@ny.cmbchina.com
Jin, Jing:		jingjin@ny.cmbchina.com
Lai, Dani:		DaniLai@ny.cmbchina.com
Lau, Richter:		RichterLau@ny.cmbchina.com
Lee, Benny:		bennylee@ny.cmbchina.com
Leung, Michelle:		michelleleung@ny.cmbchina.com
Leung, Wayne:		wayneleung@ny.cmbchina.com
Li, Field:		ShangyunLi@ny.cmbchina.com
Li, Ivy:		IvyLi@ny.cmbchina.com
Li, Jeffrey:		jeffreyli@ny.cmbchina.com
Li, Larry:		LarryLi@ny.cmbchina.com
Li, Lisa:		jingli@ny.cmbchina.com
Li, Marina:		marinali@ny.cmbchina.com
Li, Ryan:		biaoli@ny.cmbchina.com
Li, Sherry:		sherryli@ny.cmbchina.com
Li, Vivian:  VivianLi@ny.cmbchina.com
Li, Yang:		YangLi@ny.cmbchina.com
Liang, Yunwei:		yunweiliang@ny.cmbchina.com
Liu, Donald:		donaldliu@ny.cmbchina.com
Liu, Kevin:		ChaoLiu@ny.cmbchina.com
Liu, Lyman:		ZijieLiu@ny.cmbchina.com
Liu, Robin:		XunweiLiu@ny.cmbchina.com
Liu, Sharon:		sharonliu@ny.cmbchina.com
Liu, Steven:		stevenliu@ny.cmbchina.com
Liu, Yuzhao:		yuzhaoliu@ny.cmbchina.com
Loffredo, Joseph:		josephloffredo@ny.cmbchina.com
Lu, Adele:		adelelu@ny.cmbchina.com
Lu, Jalen:		jalenlu@ny.cmbchina.com
Lu, Taoyu:		TaoyuLu@ny.cmbchina.com
Lu, Yinan:		yinanlu@ny.cmbchina.com
Lu,Lucy:		lucylu@ny.cmbchina.com
Ma, Anthony:		AnthonyMa@ny.cmbchina.com
Ma, Marissa:		marissama@ny.cmbchina.com
Ma, Migo:		HongxiMa@ny.cmbchina.com
Mak, Ann:		AnnMak@ny.cmbchina.com
Mank, Celeste:		celestemank@ny.cmbchina.com
Mao, Andrew:		andrewmao@ny.cmbchina.com
Matossian, Ronald:		ronaldmatossian@ny.cmbchina.com
Miroslav Visic:		MiroslavVisic@ny.cmbchina.com
Qu, Aubrey:		WenxueQu@ny.cmbchina.com
Ray Liu:		rayliu@ny.cmbchina.com
Ren, Louis:		louisren@ny.cmbchina.com
Shi, Carl:		carlshi@ny.cmbchina.com
Shuiling Geng:		ShuilingGeng@ny.cmbchina.com
Siegel, David:		davidsiegel@ny.cmbchina.com
Song, Danny:		DannySong@ny.cmbchina.com
Song, Sharon:		sharonsong@ny.cmbchina.com
Sun, Brian:		briansun@ny.cmbchina.com
Sun, David:		YufanSun@ny.cmbchina.com
Tang, Joann:		joanntang@ny.cmbchina.com
Tang, Tiffany:		tiffanytang@ny.cmbchina.com
Tang, William:		williamtang@ny.cmbchina.com
Theophilus, Sofia:		sofiatheophilus@ny.cmbchina.com
Tian, Rebecca:		TianYi@ny.cmbchina.com
Tsui, Tessa:		tessatsui@ny.cmbchina.com
Walkiewicz, John:		johnwalkiewicz@ny.cmbchina.com
Wang, Brian:		brianwang@ny.cmbchina.com
Wang, Cindy:		xiwang@ny.cmbchina.com
Wang, Danping:		danpingwang@ny.cmbchina.com
Wang, Eddy:		eddywang@ny.cmbchina.com
Wang, Linda:		lindawang@ny.cmbchina.com
Wang, Sarah:		sarahwang@ny.cmbchina.com
Wang, Xin:		xinwang@ny.cmbchina.com
Wei, Dong:		dongwei@ny.cmbchina.com
Wei, Sophie:		weixing@ny.cmbchina.com
Wen, Renna:		rennawen@ny.cmbchina.com
Wu, Emily:		emilywu@ny.cmbchina.com
Wu, Minqiang:		MinqiangWu@ny.cmbchina.com
Xu, Josie:		JosieXu@ny.cmbchina.com
Xu, Vivian:		vivianxu@ny.cmbchina.com
Yan, Shasha:		ShaShaYan@ny.cmbchina.com
Yang, Frank:		FanYang@ny.cmbchina.com
Ye, Joyce:		HRIntern@ny.cmbchina.com
Yin, Nina:		ninayin@ny.cmbchina.com
Yuan, Jay:		JayYuan@ny.cmbchina.com
Yuen, Douglas:		DouglasYuen@ny.cmbchina.com
Zeng, Cheng:		chengzeng@ny.cmbchina.com
Zhang, Aaron:		KainanZhang@ny.cmbchina.com
Zhang, Ariel:		ArielZhang@ny.cmbchina.com
Zhang, Grace:		gracezhang@ny.cmbchina.com
Zhang, Roy:		YichiZhang@ny.cmbchina.com
Zhang, Wensi:		WensiZhang@ny.cmbchina.com
Zhang, Yeye:		ShiyueZhang@ny.cmbchina.com
Zhao, Christina:		JiaweiZhao@ny.cmbchina.com
Zhao, Yixun:		yixunzhao@ny.cmbchina.com
Zhao, Yunhan:		YunhanZhao@ny.cmbchina.com
Zhen, John:		jianzhen@ny.cmbchina.com
Zheng, Qi:		qizheng@ny.cmbchina.com
Zheng, Shawny:		shawnyzheng@ny.cmbchina.com
Zonca, Alberto:		AlbertoZonca@ny.cmbchina.com
